version: '3.9'
name: 'medicine'

services:
  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "3001:3000"
  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - "8083:81"
    links:
      - redis
      - postgres
    depends_on:
      - redis
      - postgres
    volumes:
      - ./backend/data/files:/code/data/files
      - ./backend/migrations:/code/migrations
  bot:
    build: ./bot
    restart: unless-stopped
    links:
      - redis
      - postgres
    depends_on:
      - redis
      - postgres
  redis:
    image: redis:alpine
    restart: unless-stopped
    expose:
     - 6379
    volumes:
      - "redis:/data/cache"
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: 256128
      POSTGRES_USER: postgres
      POSTGRES_DB: medicine
    expose:
      - 5432
    volumes:
      - "postgres:/data/db"
      - ./db_dump.sql:/docker-entrypoint-initdb.d/db_dump.sql

volumes:
  redis:
  postgres:
    
