import Head from "next/head";
import styles from '../styles/Start.module.css';
import { SideMenu } from "../components";
import '@fontsource-variable/inter';
import { Image } from "@chakra-ui/react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Medicine</title>
        <meta name="description" content="Generated by Zvir" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <SideMenu />
        <div className={styles.mainBlock}>
          <div className={styles.container_title} >
            <p className={styles.mainTitle} >Изучай медицину с нами. Будущее врачей начинается здесь!</p>
            <Image src='./doctorHead.png' className={styles.img1} />
          </div>
          <div className={styles.container_text} >
            <p className={styles.mainText} >Медицина - ваш надежный партнер в обучении медицинским наукам. Наш сайт предлагает студентам медицинских вузов качественные материалы, интерактивные уроки и ресурсы для успешного обучения. Присоединяйтесь к нам и готовьтесь к блестящей карьере в медицине!</p>
          </div>
          <Image src='./stethoscope.png' className={styles.img2} />
        </div>
      </main>

    </>
  );
}
